### ISSUE TITLE
php-vcr 1.5 support

### ISSUE THREAD

**Issue by allejo** [allejo/php-vcr-sanitizer#19]
Since php-vcr is back under active development (https://github.com/php-vcr/php-vcr/issues/304), let's watch closely to see what has changed in 1.5 and if anything needs to happen on this package's side.

**Comment by JeroenVanOort** [comment]
At the moment, php-vcr-sanitizer can't be installed with the 1.5.0 alpha's when version 5 of the `symfony/event-dispatcher` is used, as php-vcr-sanitizer doesn't support it. That's all I've been able to test for now.

**Comment by allejo** [comment]
@JeroenVanOort I have created the `feature/vcr-1.5-support` branch which has `^5.0` in the supported version list of `event-dispatcher`, so testing against that branch should work now.

Also, thank you for taking over `php-vcr`! :heart:
