### ISSUE TITLE
Using Response `bodyScrubbers` Creates SoapFault

### ISSUE THREAD

**Issue by danieltjewett** [allejo/php-vcr-sanitizer#27]
As an example:

```
VCRCleaner::enable([
     'request' => [
         'ignoreHostname' => false,
         'ignoreQueryFields' => [],
         'ignoreHeaders' => [],
         'bodyScrubbers' => [
             function($body) {
                  ...
                  return $body;
             }
         ],
         'postFieldScrubbers' => [
             function(array $postFields) {
                  ...
                  return $postFields;
             }
         ],
     ],
     'response' => [
         'ignoreHeaders' => ['*'],
         'bodyScrubbers' => [
              function($body) {
                  ...
                  return $body;
             }
         ],
     ],
]);
```

When running tests that actually manipulate the request body (i.e. it _finds_ and replaces it), we get `SoapFault: looks like we got no XML document`.  The replacer looks something like this:

`$body = preg_replace('/<Node>.*<\/Node>/', '<Node>REDACTED</Node>', $body);`

We even tried `mb_ereg_replace`, because we thought it might have something to do with [BOM](https://stackoverflow.com/questions/4313952/soap-looks-like-we-got-no-xml-document).

Any advice / help would be greatly appreciated.  Note, the `bodyScrubbers` for Request works fine.

**Comment by danieltjewett** [comment]
Even when we run my `preg_replace` outside of the codebase, and after the file is already written, we still get this error.  So we are thinking it is not actually with the library.

**Comment by danieltjewett** [comment]
It seems like my regex needed the `U` option.

`$body = preg_replace('/<Node>.*<\/Node>/U', '<Node>REDACTED</Node>', $body);`

It was grabbing too much without it.  For example:

`<node>Sensitive</node><Some>Other</Some><node>Sensitive</node>` was matching this whole string, when we wanted to only match `<node>Sensitive</node>`.

Sorry to bother!  Hope this helps someone else in the future.  Great library!

**Comment by allejo** [comment]
Glad you were able to figure out the problem! Yeah, usually, when you use `.*` in a regex, you want to make it non-greedy by either using the `U` flag as you discovered OR using the question mark like so, `.*?`. Otherwise, it will eat up too much.

Edit: I realize in the README I had a greedy regex, so I made it non-greedy in https://github.com/allejo/php-vcr-sanitizer/commit/44afbd4027b7fe28c6165db468816b7915bfb940
