### ISSUE TITLE
Add support for modifying response bodies and headers

### ISSUE THREAD

**Issue by allejo** [allejo/php-vcr-sanitizer#3]
Sometimes in response bodies, sensitive information may be returned. As an example, what if an API returns emails or IP addresses in the response body. There should be a way manipulate the response body.

**Comment by allejo** [comment]
The `Response` object in the VCR namespace doesn't have a way to set any information like the `Request` objects do.

Since I don't want to get into making something real hacky, I'll put this issue on hold until we can come up with something better.

**Comment by pfuhrmann** [comment]
@allejo What about using `VCREvents::VCR_AFTER_HTTP_REQUEST` event which has both `Request` and `Response`?

Edit: Modifying the response body would be useful for us. Also hiding request hostname which is currently not possible?

**Comment by allejo** [comment]
`VCREvents::VCR_BEFORE_RECORD` provides both the `Request` and `Response` objects, the problem is that `Response` doesn't have a `setBody()` method where I can modify the response. I'd have to use reflection and start modifying private variables, which I'm not a huge fan because it's bad practice and can break easily should php-vcr change how the `Response` object looks.

Though... I guess php-vcr doesn't see *too* much development activity so it's unlikely it would change often.

> Also hiding request hostname which is currently not possible?

Sure, that should be doable.

**Comment by pfuhrmann** [comment]
I understand what you mean. Maybe we could just recreate that `Response` object from scratch to prevent reflection? Something like:

```php
$new = new Vcr/Response($status = $old->getStatus(), $headers = $old->getHeaders(), $body = $sanitizedBody);
```

**Comment by allejo** [comment]
The problem with that would be that we can't tell php-vcr to use the newly created one instead of the old one unless we use reflection on the `BeforeRecordEvent` object because there's no `BeforeRecordEvent::setResponse()`.

**Comment by allejo** [comment]
@pfuhrmann I've added a new 'redactHostname' option to the `$options` array in `VCRCleaner::enable()` in 1b65aaca439ff093e8eb0aeb06b005f987d11f63. If you'd be so kind to give it a shot and let me know if it suits your needs and/or of any bugs you may find 👍

```php
VCRCleaner::enable(array(
    'redactHostname' => true,
));
```

I'll revisit modifying the `Response` via reflection tonight and hope for the best 🤞

**Comment by pfuhrmann** [comment]
@allejo thanks for this! I have tried `redactHostname` and it works for me +1 Are you going to release it as `1.0.0` or you will tag some version in between (`0.1.0`)?

**Comment by allejo** [comment]
> Are you going to release it as `1.0.0` or you will tag some version in between (`0.1.0`)?

I think I'll tag this as 0.0.2 since the behavior/config name for it is subject to change for 1.0.0

**Comment by allejo** [comment]
Actually before I tag `0.0.2`, see [my comment here](https://github.com/allejo/php-vcr-sanitizer/issues/6#issuecomment-452360908). Should I keep `[redacted]` for hostnames or replace it with `null` instead?
